<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="SDGL691" name="Full" tests="14" failures="1" timestamp="11 Sep 2014 19:14:37 GMT" time="93.809" errors="0">
  <testcase name="linuxTest" time="13.017" classname="com.rediff.testcases.QuickTestLinFF"/>
  <testcase name="testApp1" time="0.001" classname="com.rediff.testcases.RandomTest"/>
  <testcase name="testApp2" time="0.0" classname="com.rediff.testcases.RandomTest"/>
  <testcase name="testApp3" time="0.001" classname="com.rediff.testcases.RandomTest"/>
  <testcase name="windowsTest" time="10.663" classname="com.rediff.testcases.QuickTestWinFF"/>
  <testcase name="googleCheeseExample" time="7.159" classname="com.rediff.testcases.Selenium2ExampleST"/>
  <testcase name="test1" time="8.692" classname="com.rediff.testcases.Test1"/>
  <testcase name="test1_2" time="1.553" classname="com.rediff.testcases.Test1"/>
  <testcase name="googleMilkExample" time="8.777" classname="com.rediff.testcases.Selenium2ExampleST"/>
  <testcase name="test1_3" time="2.891" classname="com.rediff.testcases.Test1">
    <failure type="java.lang.AssertionError" message="expected [abc] but found [ab]">
      <![CDATA[java.lang.AssertionError: expected [abc] but found [ab]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at com.rediff.testcases.Test1.test1_3(Test1.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- test1_3 -->
  <testcase name="test1_4" time="1.495" classname="com.rediff.testcases.Test1"/>
  <testcase name="test2" time="7.898" classname="com.rediff.testcases.Test2"/>
  <testcase name="test3" time="14.85" classname="com.rediff.testcases.Test3"/>
  <testcase name="test4" time="33.853" classname="com.rediff.testcases.Test4"/>
</testsuite> <!-- Full -->
